# Generated by Django 3.1.8 on 2021-06-23 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tvshows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='../static/images/no-image.png', upload_to='tvshow_img')),
                ('image_link', models.CharField(default='None', max_length=1000)),
                ('title', models.CharField(max_length=250, null=True)),
                ('language', models.CharField(default='English', max_length=250)),
                ('rate', models.CharField(max_length=250, null=True)),
                ('trailer', models.CharField(max_length=250, null=True)),
                ('genre', models.CharField(choices=[('Action', 'Action'), ('Animation', 'Animation'), ('Crime', 'Crime'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Documentary', 'Documentary'), ('Family', 'Family'), ('Horror', 'Horror'), ('Romance', 'Romance'), ('Sci-fi', 'Sci-fi')], max_length=250, null=True)),
                ('year', models.IntegerField()),
                ('added_on', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(max_length=5000, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.SmallIntegerField(null=True)),
                ('episode_number', models.SmallIntegerField(null=True)),
                ('subtitle_download_link', models.CharField(max_length=500, null=True)),
                ('added_on', models.DateTimeField(auto_now=True)),
                ('tvshow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tvshow_subtitle_related', to='tvshows.tvshows')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.SmallIntegerField(null=True)),
                ('episode_number', models.SmallIntegerField(null=True)),
                ('episode_download_link', models.CharField(max_length=500, null=True)),
                ('added_on', models.DateTimeField(auto_now=True)),
                ('tvshow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tvshow_related', to='tvshows.tvshows')),
            ],
        ),
    ]
