# Generated by Django 3.1.8 on 2021-06-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0002_auto_20210625_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshows',
            name='slider_image_link',
            field=models.CharField(default='None', max_length=1000),
        ),
    ]
