# Generated by Django 3.1.8 on 2021-06-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvshows', '0003_tvshows_slider_image_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshows',
            name='slider_image_link',
            field=models.CharField(max_length=1000),
        ),
    ]
